//
//  ToDoListRouter.swift
//  ToDoVIP
//
//  Created by Ozan Barış Günaydın on 29.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ToDoListRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ToDoListDataPassing {
  var dataStore: ToDoListDataStore? { get }
}

class ToDoListRouter: NSObject, ToDoListRoutingLogic, ToDoListDataPassing {
  weak var viewController: ToDoListViewController?
  var dataStore: ToDoListDataStore?
    
    // Routing logics can be added
}
